### ISSUE TITLE
Feedback from Sayanti and Marcelle

### ISSUE THREAD

**Issue by mchiriboga** [UBC-MDS/worldly-wines#16]
Good job guys! We really like your app design, also we appreciate the tooltip and the filter structure.
Some suggestions we have are:
- Show the legend only once, since you are using the same colours for each category in all analysis
- Include the ’wine type’ in the tooltip that appears when the user hovers the mouse over a data point from the scatterplot
- Use alpha on the scatterplot in order to avoid overplotting
- Provide a brief explanation of the criteria to classify a wine in low, medium and high quality
- Rethink the density plot in order to make the analysis easier to understand 
- Add usage tab
- Rethink the choice of how many countries to analyze at the same time
- Fix the overwriting of the menu on the chart titles

**Comment by EvanYathon** [comment]
Hi guys, thanks for the feedback!
Here's what we implemented from your suggestions:
- made the legend only appear once
- included more hover information on crossplot
- Changed country to only one dropdown item

On our wishlist are your other items, but due to time they might have to wait for milestone4.  Thanks!
